# Site settings
title: "Caudata"
email: caudata.github@gmail.com
description: "Somewhere to think about new-t things"
baseurl: ""
url: "http://cau-data.github.io/"
title_description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris feugiat varius lorem, rhoncus ultricies tortor egestas et. Mauris consectetur risus sit amet felis ornare aliquet. Proin ullamcorper, enim non lacinia porttitor, ex leo scelerisque arcu, non ultrices erat turpis et est. Donec tempus interdum purus. Ut rhoncus odio at neque sollicitudin gravida. Morbi convallis, justo et tincidunt ullamcorper, odio dui finibus nulla, tempus dictum tellus justo non risus. Sed ultricies aliquet orci, in placerat dolor pulvinar vitae. Pellentesque lectus velit, varius in elit sed, vulputate gravida odio. Vivamus efficitur porttitor volutpat. Ut sit amet mattis ante. Nulla condimentum nisi nunc, ac ornare risus ornare vel. Proin id erat non orci ornare vulputate quis eget sem. Nullam pretium eu erat nec aliquet. Aenean sagittis varius velit quis sodales. Nunc ornare, arcu non pharetra lobortis, magna nibh aliquet ante, ut semper libero ipsum sit amet elit. Duis vestibulum tortor a sem mollis rutrum."
title_image: "https://img15.hostingpics.net/pics/149458logo.png"
#title_image: "https://img15.hostingpics.net/pics/419404logo2.png"
google_analytics: "UA-20365477-4"
disqus_account: cartenoire
github_repository: https://github.com/cau-data
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
twitter_username: caudatas
github_username: cau-data
instagram_username: 
reddit_username: 
linkedin_link: https://www.linkedin.com/in/tess-berthier-9b998090/
google_plus_link: 
stackoverflow_link: 
xing_link:
facebook_link:

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/cau-data">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
